//
// Created by tv on 03.12.23.
//

#pragma once

#include<string>
#include<cstdint>

struct WeaponInfo {
    std::string name;
    uint32_t id;
};

inline std::array<WeaponInfo, 105> c_weapons = {
        {
                {"FF No Weapon", 0xFFFFFFFF},
                {"00 Sploosh-O-Matic", 0x00},
                {"01 Neo Sploosh-O-Matic", 0x01},
                {"02 Sploosh-O-Matic 7", 0x02},
                {"03 Splattershot Jr.", 0x03},
                {"04 Custom Splattershot Jr.", 0x04},
                {"05 Splash-O-Matic", 0x05},
                {"06 Neo Splash-O-Matic", 0x06},
                {"07 Aerospray MG.", 0x07},
                {"08 Aerospray RG", 0x08},
                {"09 Aerospray PG", 0x09},
                {"0A Splattershot", 0x0A},
                {"0B Tentatek Splattershot", 0x0B},
                {"0C Wasabi Splattershot", 0x0C},
                {"0D Hero Shot Replica", 0x0D},
                {"0E Octoshot Replica", 0x0E},
                {"0F .52 Gal", 0x0F},
                {"10 .52 Gal Deco", 0x10},
                {"11 N Zap 85", 0x11},
                {"12 N Zap 89", 0x12},
                {"13 N Zap 83", 0x13},
                {"14 Splattershot Pro", 0x14},
                {"15 Forge Splattershot Pro", 0x15},
                {"16 Berry Splattershot Pro", 0x16},
                {"17 .96 Gal", 0x17},
                {"18 .96 Gal Deco", 0x18},
                {"19 Dual Squelcher", 0x19},
                {"1A Custom Dual Squelcher", 0x1A},
                {"1B Jet Squelcher", 0x1B},
                {"1C Custom Jet Squelcher", 0x1C},
                {"1D Luna Blaster", 0x1D},
                {"1E Luna Blaster Neo", 0x1E},
                {"1F Blaster", 0x1F},
                {"20 Custom Blaster", 0x20},
                {"21 Range Blaster", 0x21},
                {"22 Custom Range Blaster", 0x22},
                {"23 Grim Range Blaster", 0x23},
                {"24 Rapid Blaster", 0x24},
                {"25 Rapid Blaster Deco", 0x25},
                {"26 Rapid Blaster Pro", 0x26},
                {"27 Rapid Blaster Pro Deco", 0x27},
                {"28 L-3 Nozzlenose", 0x28},
                {"29 L-3 Nozzlenose D", 0x29},
                {"2A H-3 Nozzlenose", 0x2A},
                {"2B H-3 Nozzlenose D", 0x2B},
                {"2C Cherry H-3 Nozzlenose", 0x2C},
                {"2D Carbon Roller", 0x2D},
                {"2E Carbon Roller Deco", 0x2E},
                {"2F Splat Roller", 0x2F},
                {"30 Krak-On Splat Roller", 0x30},
                {"31 CoroCoro Splat Roller", 0x31},
                {"32 Hero Roller Replica", 0x32},
                {"33 Dynamo Roller", 0x33},
                {"34 Gold Dynamo Roller", 0x34},
                {"35 Tempered Dynamo Roller", 0x35},
                {"36 Inkbrush", 0x36},
                {"37 Inkbrush Nouvou", 0x37},
                {"38 Permanent Inkbrush", 0x38},
                {"39 Octobrush", 0x39},
                {"3A Octobrush Nouveau", 0x3A},
                {"3B Classic Squiffer", 0x3B},
                {"3C New Squiffer", 0x3C},
                {"3D Fresh Squiffer", 0x3D},
                {"3E Splat Charger", 0x3E},
                {"3F Kelp Splat Charger", 0x3F},
                {"40 Bento Splat Charger", 0x40},
                {"41 Hero Charger Replica", 0x41},
                {"42 Splatterscope", 0x42},
                {"43 Kelp Splatterscope", 0x43},
                {"44 Bento Splatterscope", 0x44},
                {"45 E-Liter 3K", 0x45},
                {"46 Custom E-Liter 3K", 0x46},
                {"47 E-Liter 3K Scope", 0x47},
                {"48 Custom E-Liter 3K Scope", 0x48},
                {"49 Bamboozler MK I", 0x49},
                {"4A Bamboozler MK II", 0x4A},
                {"4B Bamboozler MK III", 0x4B},
                {"4C Slosher", 0x4C},
                {"4D Slosher Deco", 0x4D},
                {"4E Soda Slosher", 0x4E},
                {"4F Tri-Slosher", 0x4F},
                {"50 Tri-Slosher Nouveau", 0x50},
                {"51 Sloshing Machine", 0x51},
                {"52 Sloshing Machine Neo", 0x52},
                {"53 Mini Splatling", 0x53},
                {"54 Zink Mini Splatling", 0x54},
                {"55 Refurbished Mini Splatling", 0x55},
                {"56 Heavy Splatling", 0x57},
                {"57 Heavy Splatling Deco", 0x57},
                {"58 Heavy Splatling Remix", 0x58},
                {"59 Hydra Splatling", 0x59},
                {"5A Custom Hydra Splatling", 0x5A},
                {"5B Hero Shot Lvl0", 0x5B},
                {"5C Hero Shot Lvl1", 0x5C},
                {"5D Hero Shot Lvl2", 0x5D},
                {"5E Hero Shot Lvl3", 0x5E},
                {"5F Hero Roller", 0x5F},
                {"60 Hero Charger", 0x60},
                {"61 BigBallA", 0x61},
                {"62 BigBallB", 0x62},
                {"63 Octoshot Lvl0", 0x63},
                {"64 Octoshot Lvl1", 0x64},
                {"65 Octoshot Lvl2", 0x65},
                {"66 Octoshot Lvl3", 0x66},
                {"67 Roller Kingsquid", 0x67}
        }
};

static WeaponInfo c_subWeapons[] = {
        {"00 Splat Bomb",    0x00},
        {"01 Sucction Bomb", 0x01},
        {"02 Burst Bomb",    0x02},
        {"03 Seeker",        0x03},
        {"04 Point Sensor",  0x04},
        {"05 Ink Mine",      0x05},
        {"06 Sprinkler",     0x06},
        {"07 Squid Beakon",  0x07},
        {"08 Splash Wall",   0x08},
        {"09 Disruptor",     0x09},
        {"FFFFFFFF None",    0xFFFFFFFF}
};

static WeaponInfo c_specialWeapons[] = {
        {"00 Inkzooka",            0x00},
        {"02 Killer Wail",         0x01},
        {"02 Inkstrike",           0x02},
        {"03 Bubbler",             0x03},
        {"04 Bomb Rush",           0x04},
        {"05 Kraken",              0x05},
        {"06 Echo",                0x06},
        {"07 Gachihoko/Rainmaker", 0x07},
        {"FFFFFFFF None",          0xFFFFFFFF}
};

inline std::array<WeaponInfo, 105> weaponIds = {
        {
                {"FF No Weapon", 0xFFFFFFFF},
                {"00 Sploosh-O-Matic", 100},
                {"01 Neo Sploosh-O-Matic", 101},
                {"02 Sploosh-O-Matic 7", 140},
                {"03 Splattershot Jr.", 102},
                {"04 Custom Splattershot Jr.", 103},
                {"05 Splash-O-Matic", 104},
                {"06 Neo Splash-O-Matic", 105},
                {"07 Aerospray MG.", 106},
                {"08 Aerospray RG", 107},
                {"09 Aerospray PG", 141},
                {"0A Splattershot", 108},
                {"0B Tentatek Splattershot", 109},
                {"0C Wasabi Splattershot", 138},
                {"0D Hero Shot Replica", 110},
                {"0E Octoshot Replica", 111},
                {"0F .52 Gal", 112},
                {"10 .52 Gal Deco", 113},
                {"11 N Zap 85", 114},
                {"12 N Zap 89", 115},
                {"13 N Zap 83", 142},
                {"14 Splattershot Pro", 116},
                {"15 Forge Splattershot Pro", 117},
                {"16 Berry Splattershot Pro", 139},
                {"17 .96 Gal", 118},
                {"18 .96 Gal Deco", 119},
                {"19 Dual Squelcher", 120},
                {"1A Custom Dual Squelcher", 121},
                {"1B Jet Squelcher", 122},
                {"1C Custom Jet Squelcher", 123},
                {"1D Luna Blaster", 124},
                {"1E Luna Blaster Neo", 125},
                {"1F Blaster", 126},
                {"20 Custom Blaster", 127},
                {"21 Range Blaster", 128},
                {"22 Custom Range Blaster", 129},
                {"23 Grim Range Blaster", 143},
                {"24 Rapid Blaster", 130},
                {"25 Rapid Blaster Deco", 131},
                {"26 Rapid Blaster Pro", 132},
                {"27 Rapid Blaster Pro Deco", 133},
                {"28 L-3 Nozzlenose", 134},
                {"29 L-3 Nozzlenose D", 135},
                {"2A H-3 Nozzlenose", 136},
                {"2B H-3 Nozzlenose D", 137},
                {"2C Cherry H-3 Nozzlenose", 144},
                {"2D Carbon Roller", 200},
                {"2E Carbon Roller Deco", 201},
                {"2F Splat Roller", 202},
                {"30 Krak-On Splat Roller", 203},
                {"31 CoroCoro Splat Roller", 213},
                {"32 Hero Roller Replica", 204},
                {"33 Dynamo Roller", 205},
                {"34 Gold Dynamo Roller", 206},
                {"35 Tempered Dynamo Roller", 211},
                {"36 Inkbrush", 207},
                {"37 Inkbrush Nouvou", 208},
                {"38 Permanent Inkbrush", 212},
                {"39 Octobrush", 209},
                {"3A Octobrush Nouveau", 210},
                {"3B Classic Squiffer", 300},
                {"3C New Squiffer", 301},
                {"3D Fresh Squiffer", 313},
                {"3E Splat Charger", 302},
                {"3F Kelp Splat Charger", 303},
                {"40 Bento Splat Charger", 315},
                {"41 Hero Charger Replica", 304},
                {"42 Splatterscope", 305},
                {"43 Kelp Splatterscope", 306},
                {"44 Bento Splatterscope", 316},
                {"45 E-Liter 3K", 307},
                {"46 Custom E-Liter 3K", 308},
                {"47 E-Liter 3K Scope", 309},
                {"48 Custom E-Liter 3K Scope", 310},
                {"49 Bamboozler MK I", 311},
                {"4A Bamboozler MK II", 312},
                {"4B Bamboozler MK III", 314},
                {"4C Slosher", 400},
                {"4D Slosher Deco", 401},
                {"4E Soda Slosher", 406},
                {"4F Tri-Slosher", 402},
                {"50 Tri-Slosher Nouveau", 403},
                {"51 Sloshing Machine", 404},
                {"52 Sloshing Machine Neo", 405},
                {"53 Mini Splatling", 500},
                {"54 Zink Mini Splatling", 501},
                {"55 Refurbished Mini Splatling", 506},
                {"56 Heavy Splatling", 502},
                {"57 Heavy Splatling Deco", 503},
                {"58 Heavy Splatling Remix", 507},
                {"59 Hydra Splatling", 504},
                {"5A Custom Hydra Splatling", 505},
                {"5B Hero Shot Lvl0", 1000},
                {"5C Hero Shot Lvl1", 1001},
                {"5D Hero Shot Lvl2", 1002},
                {"5E Hero Shot Lvl3", 1003},
                {"5F Hero Roller", 1100},
                {"60 Hero Charger", 1200},
                {"61 BigBallA", 1800},
                {"62 BigBallB", 1801},
                {"63 Octoshot Lvl0", 2000},
                {"64 Octoshot Lvl1", 2001},
                {"65 Octoshot Lvl2", 2002},
                {"66 Octoshot Lvl3", 2003},
                {"67 Roller Kingsquid", 5000}
        }
};


inline std::array<WeaponInfo, 35> subWeaponIds = {
	{
        {"Splat Bomb",    0},
        {"Sucction Bomb", 1},
        {"Burst Bomb",    2},
        {"Seeker",        3},
        {"Point Sensor",  4},
        {"Ink Mine",      5},
        {"Sprinkler",     6},
        {"Squid Beakon",  7},
        {"Splash Wall",   8},
        {"Disruptor",     9},
        {"Hero Splat Bomb Lvl0",1000},
        {"Hero Splat Bomb Lvl1",1001},
        {"Hero Splat Bomb Lvl2",1002},
        {"Hero Splat Bomb Lvl3",1003},
        {"Hero Burst Bomb Lvl0",1100},
        {"Hero Burst Bomb Lvl1",1101},
        {"Hero Burst Bomb Lvl2",1102},
        {"Hero Burst Bomb Lvl3",1103},
        {"Hero Seeker Bomb Lvl0",1200},
        {"Hero Seeker Bomb Lvl1",1201},
        {"Hero Seeker Bomb Lvl2",1202},
        {"Hero Seeker Bomb Lvl3",1203},
        {"FFFFFFFF None",    0xFFFFFFFF}
	}
};

inline std::array<WeaponInfo, 12> specialWeaponIds = {
	{
        {"Inkzooka",            0},
        {"Killer Wail",         1},
        {"Inkstrike",           2},
        {"Bubbler",             3},
        {"Bomb Rush",           4},
        {"Kraken",              5},
        {"Echo",                6},
        {"Gachihoko/Rainmaker", 7},
        {"FFFFFFFF None",          0xFFFFFFFF}
	}
};
